### PR TITLE
Add Create and Delete topic

### PR DESCRIPTION
**Pull request by epipho**
Deals with about half of #7
- Includes validation for partition assignments as prep for manual partition reassignment
- Includes functional tests

/cc @frosenberg

### CODE REVIEW

**Comment by F21** [comment]
ping @wvanbergen Any chance this could be merged?

**Comment by wvanbergen** [comment]
Looks like Travis didn't run CI on this pull request. This issue should be fixed now. Can you rebase this PR and try again?

**Comment by F21** [comment]
Should be superseded by #25.

**Comment by F21** [comment]
This can be closed as #25 was merged.

**Comment by wvanbergen** [comment]
Thanks!

**Pull request closed without merging**
