### PR TITLE
TML-11943 Improves Kazoo logging

### PR DESCRIPTION
**Pull request by F21**
Carrying #16

### CODE REVIEW

**Comment by F21** [comment]
Tests appear to pass for this one.

**Comment by wvanbergen** [comment]
Any chance you can paste a sample of the logging this generates?

**Comment by F21** [comment]
Unfortunately, I don't currently have an environment to set the whole thing up to test it out.

**Comment by F21** [comment]
Just dug into the code for this one.

This is what the logging generates:
```
2016/09/30 11:19:57 Connected to 127.0.0.1:2181
2016/09/30 11:19:57 Authenticated: id=96680960823394309, timeout=6000
2016/09/30 11:19:57 Re-submitting `0` credentials after reconnect
2016/09/30 11:19:57 Recv loop terminated: err=EOF
2016/09/30 11:19:57 Send loop terminated: err=<nil>
```
See the all the logs in the test-run on travis: https://travis-ci.org/wvanbergen/kazoo-go/jobs/163984543

The behaviour is exactly the same as the current behaviour without this change, as the zk client automatically sets the `DefaultLogger` as the logger if no logger is passed in. See my other PR where the zk client also logs to output, despite no logger being set: https://travis-ci.org/wvanbergen/kazoo-go/builds/163991217

**Comment by tosan88** [comment]
Hi! Any plans to release this change?

**Comment by wvanbergen** [comment]
Sorry for the late response. I have not been actively maintaining this library, and am working in a different field these days, so PR reviews will be slow as a result.

**Pull request merged**
