### PR TITLE
TML-11943 Improves Kazoo logging

### PR DESCRIPTION
**Pull request by mstovicek**

### CODE REVIEW

**Comment by wvanbergen** [comment]
Thanks!

Is it possible to leave the logger to `nil`?

**Comment by F21** [comment]
@wvanbergen Do you mean setting the logger returned in the config when calling `NewConfig()` to nil? If so, I can carry this one.

**Comment by wvanbergen** [comment]
What I mean is that things will not break if I completely ignore the `Logger` setting, which in practice means the value will be `nil`.

**Comment by wvanbergen** [comment]
Also, if we rebase this PR, we will get a Travis CI run for this as well.

**Comment by F21** [comment]
Superseded by #26

**Comment by F21** [comment]
This can be closed as #26 was merged.

**Comment by mstovicek** [comment]
Cool, thanks for getting it in eventually :)

**Pull request closed without merging**
